# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from db.models import session
from db.models import Organisation
from interface.index_interface import *


class Ui_AdminWindow(object):
    user = None
    logout_page = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 574)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_routes_interface_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_routes_interface_2.setGeometry(QtCore.QRect(90, 370, 391, 41))
        self.button_routes_interface_2.setObjectName("button_routes_interface_2")
        self.button_routes_interface = QtWidgets.QPushButton(self.centralwidget)
        self.button_routes_interface.setGeometry(QtCore.QRect(90, 250, 391, 41))
        self.button_routes_interface.setObjectName("button_routes_interface")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 201, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("interface/logos/bus1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_organisation_name = QtWidgets.QLabel(self.centralwidget)
        self.label_organisation_name.setGeometry(QtCore.QRect(240, 90, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_organisation_name.setFont(font)
        self.label_organisation_name.setObjectName("label_organisation_name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_admin_name = QtWidgets.QLabel(self.centralwidget)
        self.label_admin_name.setGeometry(QtCore.QRect(240, 40, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_admin_name.setFont(font)
        self.label_admin_name.setObjectName("label_admin_name")
        self.button_income_recount = QtWidgets.QPushButton(self.centralwidget)
        self.button_income_recount.setGeometry(QtCore.QRect(90, 490, 391, 41))
        self.button_income_recount.setObjectName("button_income_recount")
        self.button_personal_interface = QtWidgets.QPushButton(self.centralwidget)
        self.button_personal_interface.setGeometry(QtCore.QRect(90, 310, 391, 41))
        self.button_personal_interface.setObjectName("button_personal_interface")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(30, 20, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.button_vehicle_interface = QtWidgets.QPushButton(self.centralwidget)
        self.button_vehicle_interface.setGeometry(QtCore.QRect(90, 190, 391, 41))
        self.button_vehicle_interface.setObjectName("button_vehicle_interface")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 160, 781, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_current_income = QtWidgets.QLabel(self.centralwidget)
        self.label_current_income.setGeometry(QtCore.QRect(240, 130, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_current_income.setFont(font)
        self.label_current_income.setObjectName("label_current_income")
        self.button_reports_interface = QtWidgets.QPushButton(self.centralwidget)
        self.button_reports_interface.setGeometry(QtCore.QRect(90, 430, 391, 41))
        self.button_reports_interface.setObjectName("button_reports_interface")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 21))
        self.menubar.setObjectName("menubar")
        self.menuLogout = QtWidgets.QMenu(self.menubar)
        self.menuLogout.setObjectName("menuLogout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionlogout = QtWidgets.QAction(MainWindow)
        self.actionlogout.setObjectName("actionlogout")
        self.actionlogout.triggered.connect(self.logout)

        self.menuLogout.addAction(self.actionlogout)
        self.menubar.addAction(self.menuLogout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_routes_interface_2.setText(_translate("MainWindow", "Open personal managment"))
        self.button_routes_interface.setText(_translate("MainWindow", "Open routes managment"))
        self.label_2.setText(_translate("MainWindow", "Organisation Name:"))
        self.label_organisation_name.setText(_translate("MainWindow", self.get_organisation_title()))
        self.label_3.setText(_translate("MainWindow", "Current Income:"))
        self.label_admin_name.setText(_translate("MainWindow", self.get_user_name()))
        self.button_income_recount.setText(_translate("MainWindow", "Recount current income"))
        self.button_personal_interface.setText(_translate("MainWindow", "Open routes managment"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome:"))
        self.button_vehicle_interface.setText(_translate("MainWindow", "Open Vehicle State"))
        self.label_current_income.setText(_translate("MainWindow", self.get_organisation_income()))
        self.button_reports_interface.setText(_translate("MainWindow", "Open reports"))
        self.menuLogout.setTitle(_translate("MainWindow", "Logout"))
        self.actionlogout.setText(_translate("MainWindow", "logout"))

    def get_organisation_title(self):
        organisation_title = session.query(Organisation).first().Title
        return organisation_title

    def get_organisation_income(self):
        organisation_income = session.query(Organisation).first().Income
        return organisation_income

    def get_user_name(self):
        fname = self.user.FirstName
        return fname

    # def logout(self):
    #     MainWindow = QtWidgets.QMainWindow()
    #     ui = Ui_MainWindow()
    #     ui.setupUi(MainWindow)
    #     MainWindow.show()
