# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from db.models import session
from db.models import Organisation

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(70, 440, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.policemen_picture = QtWidgets.QLabel(self.centralwidget)
        self.policemen_picture.setGeometry(QtCore.QRect(300, 40, 401, 431))
        self.policemen_picture.setText("")
        self.policemen_picture.setPixmap(QtGui.QPixmap(
            "interface/logos/policeman.png"
        ))
        self.policemen_picture.setScaledContents(True)
        self.policemen_picture.setObjectName("policemen_picture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        self.menuLog_in = QtWidgets.QMenu(self.menubar)
        self.menuLog_in.setObjectName("menuLog_in")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.log_as_admin = QtWidgets.QAction(MainWindow)
        self.log_as_admin.setObjectName("log_as_admin")
        self.log_as_admin.triggered.connect(self.log_as_ad)

        self.log_as_ticketsman = QtWidgets.QAction(MainWindow)
        self.log_as_ticketsman.setObjectName("log_as_ticketsman")
        self.log_as_driver = QtWidgets.QAction(MainWindow)
        self.log_as_driver.setObjectName("log_as_driver")
        self.menuLog_in.addSeparator()

        self.menuLog_in.addAction(self.log_as_admin)
        self.menuLog_in.addAction(self.log_as_ticketsman)
        self.menuLog_in.addAction(self.log_as_driver)
        self.menubar.addAction(self.menuLog_in.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label2.setText(_translate("MainWindow", "LOG IN. PLEASE"))
        self.menuLog_in.setTitle(_translate("MainWindow", "Log in"))
        self.log_as_admin.setText(_translate("MainWindow", "Log as Admin"))
        self.log_as_ticketsman.setText(_translate("MainWindow", "Log as Ticketsman"))
        self.log_as_driver.setText(_translate("MainWindow", "Log as Driver"))

    def log_as_ad(self):
        results = session.query(Organisation).all()
        print(results)

    def log_as_tick(self):
        pass

    def log_as_dr(self):
        pass


